# Configuration file for a Jekyll site
title: Kari David
# Add more site-wide configuration here

# Theme settings
theme: jekyll-theme-minimal

# Custom settings
author:
name: Kari David

# Placeholder for image
logo: /assets/img/headshot_circle.png
show_download: true
https://github.com/karidavidi/Portfolio/blob/main/wiki.images/kjh.jpg
